### ISSUE TITLE
Hang-up when installing

### ISSUE THREAD

**Issue by mindbound** [chenglou/atom-reason-loader#4]
Upon installation on Arch Linux/Atom latest stable, the plugin spawns one or more shell processes and seemingly freezes (no response in at least 1 h).

**Comment by andrewray** [comment]
I get the same issue with Ubuntu 14.04.

```
$ atom --version
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

```
$ opam --version
1.2.2
```

```
$ opam pin list
merlin.2.3.1         git  https://github.com/the-lambda-church/merlin.git#reason-0.0.1
merlin_extend.0.2    git  https://github.com/let-def/merlin-extend.git#reason-0.0.1   
reason.0.0.5         git  https://github.com/facebook/reason.git#0.0.6
```

```
$ uname -a
Linux woofer 3.13.0-86-generic #131-Ubuntu SMP Thu May 12 23:33:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jordwalke** [comment]
Thank you for reporting. Do you have any info about the shell process that are spawned and not terminating? It should be running `opam` commands to find where your `Reason` is installed in your switch, and I'm curious if those are stalled.

**Comment by chenglou** [comment]
Also, I've just made a new `linux` branch which cuts out the `environmentHelpers` part: https://github.com/chenglou/atom-reason-loader/commit/6ad2aafe15e5547f424b5fb3a52ea799403538ed

This _might_ solve your problem. Can you help us test it please? We don't have a linux machine with us. Clone the repo, switch to that branch, do `apm link` and restart Atom.

**Comment by mindbound** [comment]
Looks like the issue remains even in the `linux` branch. Upon starting, Atom launches one or more `/usr/bin/zsh -ilc env` processes (zsh is my default shell) and doesn't progress past that point.

**Comment by jordwalke** [comment]
It might be worth trying in `bash` if you can - just to give a datapoint.

**Comment by andrewray** [comment]
For me it's `/bin/bash -ilc env` that appears to hang with 100% cpu usage.

**Comment by mindbound** [comment]
Same here with `bash`.

**Comment by MatejLach** [comment]
Confirmed for me with both `bash` and `zsh` I observe the same results as @mindbound @andrewray so it doesn't apper to be an isolated issue.

**Comment by chenglou** [comment]
Btw this has been fixed.

**Comment by focmb** [comment]
This has not been fixed in the current version. The problem is still there. /bin/bash -ilc command env runs with 4 processes. Every with 100 % cpu

**Comment by jordwalke** [comment]
Can you tell us anything that would help us debug? Is it still a problem on Linux? What version of atom?

How could the simple env command ever take up that much CPU?
